name: Publish Package to NPMJS
on: 
    push: 
        branches: [ production, development ]
    release: 
        types: [published]
jobs: 
    Publish-To-NPM-JS: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
            - run: npm install

            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            - name: Publish to NPM
              shell: bash
              env: 
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  BRANCHNAME: eng:${{ steps.extract_branch.outputs.branch }}
              run: |
                  export BRANCHNAME=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
                  npm run publishToNPM